# @package _global_

train:

  model_a_type: "mean_estimator"
  model_a_hidden_fc_dims: [128, 64]
  model_a_lr: 0.01
  model_a_weight_decay: 0.0

  epochs: 500
  batch_size: ${data.samples}
  earlystopping:
    patience: 30
    delta: 0.0
